[package]
name = "railgun-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
aes = "0.8.4"
aes-gcm = "0.10.3"
alloy = "1.0.42"
alloy-contract = "1.0.42"
alloy-sol-types = "1.5.4"
ark-bn254 = "0.5.0"
ark-circom = "0.5.0"
ark-ec = "0.5.0"
ark-ed-on-bn254 = "0.5.0"
ark-ff = "0.5.0"
ark-groth16 = "0.5.0"
ark-serialize = "0.5.0"
ark-std = "0.5.0"
babyjubjub-rs = "0.0.11"
bech32 = "0.11.1"
blake = "2.0.2"
ctr = "0.9.2"
curve25519-dalek = "4.1.3"
ed25519-dalek = "2.2.0"
ff = "0.13.1"
ff_ce = "0.14.3"
hex = "0.4.3"
light-poseidon = "0.4.0"
num-bigint = "0.4.6"
poseidon-rs = "0.0.10"
rayon = "1.11.0"
reqwest = { version = "0.13", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10.9"
thiserror = "2.0.18"
tokio = { version = "1.49", features = ["full"] }
tracing = "0.1.44"
tracing-subscriber = "0.3.22"
zeroize = "1.8.2"

[dev-dependencies]
tracing-test = "0.2.5"
